[theme]
base="dark"
primaryColor="#7A0019"
backgroundColor="#0E0E0E"
secondaryBackgroundColor="#1A1A1A"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[global]
pythonVersion = "3.12"
